<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();

$customerStatus = $block->getCustomerDetails();
$customerLoggedIn = $block->getCustomerIsLoggedIn();

?>
<?php if ($block->getShowPart() == 'welcome') : ?>
    
    <li class="greet welcome" data-bind="scope: 'customer'">
        <!-- ko if: customer().fullname  -->
        <span class="logged-in"
              data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
        </span>
        <!-- /ko -->
        <!-- ko ifnot: customer().fullname  -->
        <span class="not-logged-in"
              data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
        <?= $block->getBlockHtml('header.additional') ?>
        <!-- /ko -->
    </li>
    <?php if ($customerLoggedIn) : ?>
        <?php if ($customerStatus == 1) : ?>
        <li class="customer-status"><?= $block->escapeHtml(__('Enabled')) ?></li>
        <?php else: ?>
            <li class="customer-status"><?= $block->escapeHtml(__('Disabled')) ?></li>
        <?php endif ?>
    <?php endif ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script>
<?php elseif ($block->getShowPart() == 'other') :?>
    <?= $block->getChildHtml() ?>
<?php endif ?>

